name: Close stale issues
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: 'inactive'
          days-before-issue-stale: 180
          days-before-issue-close: 365
          close-issue-message: |-
            This issue has been closed automatically. Please see https://github.com/Neamar/KISS/issues/1688 for details.
            Thank you for your contributions.
